version: '3.8'

services:
  # RabbitMQ Cluster Node 1
  rabbitmq1:
    image: "bitnami/rabbitmq:3.13.3"
    hostname: rabbitmq1
    ports:
      - "1883:1883" # MQTT port
      - "5672:5672" # AMQP port
      - "15672:15672" # Web UI
    environment:
      # Cluster configuration
      RABBITMQ_ERLANG_COOKIE: "INTERSECT_CLUSTERING_COOKIE"
      RABBITMQ_NODENAME: "rabbit@rabbitmq1"
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    volumes:
      - rabbitmq1_data:/bitnami/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - intersect_net

  # RabbitMQ Cluster Node 2
  rabbitmq2:
    image: "bitnami/rabbitmq:3.13.3"
    hostname: rabbitmq2
    ports:
      - "1884:1883" # MQTT port
      - "5673:5672" # AMQP port 
      - "15673:15672" # Web UI
    depends_on:
      rabbitmq1:
        condition: service_healthy
    environment:
      # Cluster configuration
      RABBITMQ_ERLANG_COOKIE: "INTERSECT_CLUSTERING_COOKIE"
      RABBITMQ_NODENAME: "rabbit@rabbitmq2"
      RABBITMQ_CLUSTER_NODE_NAME: "rabbit@rabbitmq1"
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    volumes:
      - rabbitmq2_data:/bitnami/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - intersect_net

  # MinIO for object storage (if needed by the example)
  minio:
    image: "bitnami/minio:2024.6.4"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - "9000:9000" # main MINIO API port
      - "9001:9001" # web UI
    networks:
      - intersect_net

volumes:
  rabbitmq1_data:
  rabbitmq2_data:

networks:
  intersect_net:
    driver: bridge