version: '3.8'

services:
  # RabbitMQ Cluster Node 1
  rabbitmq1:
    image: "bitnami/rabbitmq:3.13.3"
    hostname: rabbitmq1
    ports:
      - "1883:1883" # MQTT port
      - "5672:5672" # AMQP port
      - "15672:15672" # Web UI
    environment:
      # Cluster configuration
      RABBITMQ_ERLANG_COOKIE: "INTERSECT_CLUSTERING_COOKIE"
      RABBITMQ_NODENAME: "rabbit@rabbitmq1"
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt rabbitmq_federation"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    volumes:
      - rabbitmq1_data:/bitnami/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 30s  # Increased start period to give more time for initialization
      timeout: 10s
    networks:
      intersect_net:
        aliases:
          - rabbitmq1

  # RabbitMQ Cluster Node 2
  rabbitmq2:
    image: "bitnami/rabbitmq:3.13.3"
    hostname: rabbitmq2
    ports:
      - "1884:1883" # MQTT port
      - "5673:5672" # AMQP port
      - "15673:15672" # Web UI
    depends_on:
      rabbitmq1:
        condition: service_healthy
    environment:
      # Cluster configuration
      RABBITMQ_ERLANG_COOKIE: "INTERSECT_CLUSTERING_COOKIE"
      RABBITMQ_NODENAME: "rabbit@rabbitmq2"
      RABBITMQ_CLUSTER_NODE_NAME: "rabbit@rabbitmq1"
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt rabbitmq_federation"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    volumes:
      - rabbitmq2_data:/bitnami/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 30s  # Increased start period to give more time for initialization
      timeout: 10s
    networks:
      intersect_net:
        aliases:
          - rabbitmq2

  # MinIO for object storage (if needed by the example)
  minio:
    image: "bitnami/minio:2024.6.4"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - "9000:9000" # main MINIO API port
      - "9001:9001" # web UI
    networks:
      intersect_net:
        aliases:
          - minio

  client:
    image: intersect-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/app
      - ./python-sdk:/opt/intersect_sdk
    environment:
      PYTHONPATH: /opt/intersect_sdk
      PROTOCOL: ${PROTOCOL:-mqtt}
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for RabbitMQ cluster to fully initialize...' &&
        sleep 15 &&
        echo 'Starting client...' &&
        python /app/counting_client.py
      "
    networks:
      intersect_net:
        aliases:
          - client

  service:
    image: intersect-service
    build:
      context: .
      dockerfile: ./service/Dockerfile
    volumes:
      - ./service:/app
      - ./python-sdk:/opt/intersect_sdk
    environment:
      PYTHONPATH: /opt/intersect_sdk
      PROTOCOL: ${PROTOCOL:-mqtt}
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for RabbitMQ cluster to fully initialize...' &&
        sleep 10 &&
        echo 'Starting service...' &&
        python /app/counting_service.py
      "
    networks:
      intersect_net:
        aliases:
          - service

volumes:
  rabbitmq1_data:
  rabbitmq2_data:

networks:
  intersect_net:
    driver: bridge
    name: intersect_net